#配置注册中心
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka#只能结合云服务器才能设置其他选项，否则只能使用defaultZone

spring:
  application:
    name: item-service
    
  rabbitmq:
    host: 192.168.40.129
    port: 5672
    username: admin
    password: admin

#server:#  port: 8001
---
spring:  profiles: item1
server:  port: 8001

---
spring:
  profiles: item2
server:
  port: 8002
