#配置注册中心
eureka:
  client:
    service-url:
    #只能结合云服务器才能设置其他选项，否则只能使用defaultZone
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka 
spring:
  application:
    name: order-service
    
#server:
#  port: 8201

feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
---
spring:
  profiles: order1
  
server:
  port: 8201

---
spring:
  profiles: order2
  
server:
  port: 8202





